upstream auth_service {
    server auth-service:8001;
}

upstream master_service {
    server master-service:8002;
}

upstream admin_service {
    server admin-service:8003;
}

upstream reception_service {
    server reception-service:8004;
}

upstream triage_service {
    server triage-service:8005;
}

upstream consultation_service {
    server consultation-service:8006;
}

upstream laboratory_service {
    server laboratory-service:8007;
}

upstream radiology_service {
    server radiology-service:8008;
}

upstream pharmacy_service {
    server pharmacy-service:8009;
}

upstream billing_service {
    server billing-service:8010;
}

upstream ward_service {
    server ward-service:8011;
}

upstream notification_service {
    server notification-service:8012;
}

upstream report_service {
    server report-service:8013;
}

server {
    listen 80;
    server_name _;

    location /health {
        proxy_pass http://localhost:8000/health;
    }

    location /api/v1/auth {
        proxy_pass http://auth_service;
    }

    location /api/v1/superadmin {
        proxy_pass http://master_service;
    }

    location /api/v1/admin {
        proxy_pass http://admin_service;
    }

    location /api/v1/reception {
        proxy_pass http://reception_service;
    }

    location /api/v1/triage {
        proxy_pass http://triage_service;
    }

    location /api/v1/consultation {
        proxy_pass http://consultation_service;
    }

    location /api/v1/laboratory {
        proxy_pass http://laboratory_service;
    }

    location /api/v1/radiology {
        proxy_pass http://radiology_service;
    }

    location /api/v1/pharmacy {
        proxy_pass http://pharmacy_service;
    }

    location /api/v1/billing {
        proxy_pass http://billing_service;
    }

    location /api/v1/ward {
        proxy_pass http://ward_service;
    }

    location /api/v1/notifications {
        proxy_pass http://notification_service;
    }

    location /api/v1/reports {
        proxy_pass http://report_service;
    }
}
