[alembic]
script_location = .
prepend_sys_path = .
version_path_separator = os
timezone = UTC

[post_write_hooks]

[logging]
keys = root,sqlalchemy,alembic
handlers = console
qualname =
propagate = 0

[handlers]
keys = console
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatters]
keys = generic
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[alembic:exclude]
tables =
