from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date, timedelta

from app.assistant.language import expand_query
from app.assistant.live.contracts import MetricParams, MetricTier
from app.assistant.live.registry import MetricDefinition, permitted_metrics
from app.assistant.retrieval import _tokenize

# Which metrics run is decided here, on the server, from the words in the
# question. The model is not consulted and never sees a metric id.
#
# This reuses the tokeniser and the Swahili expansion that content retrieval
# already uses, so "how many beds are free" and "kuna vitanda vingapi wazi"
# route to the same metric without a second vocabulary to maintain.

# A patient-tier metric is only ever reached when the question carries an
# explicit identifier. A general enquiry cannot reach one patient's record.
#
# Both formats are generated by the service that owns them and are the same in
# every tenant, so they are matched exactly rather than loosely:
#
#   PT-YYYYMMDD-NNNN   patient-service/app/services/patient_number.py:49
#   VIS-YYYYMMDD-NNNN  visit-service/app/services/number_generator.py:48
#
# They were written from a guess before: "[A-Z]{2,6}-\d{2,4}-\d{3,6}", which
# cannot match an eight-digit date part, and "V-?\d{4,8}", which cannot match a
# VIS- prefix. Neither matched a real identifier, so a patient-tier metric would
# have been skipped for want of an identifier on exactly the questions that
# carried one - and a lookup that failed to resolve looks, from here, precisely
# like a general enquiry. The counter is four digits today and may grow.
PATIENT_NUMBER_PATTERN = r"PT-\d{8}-\d{3,8}"
VISIT_NUMBER_PATTERN = r"VIS-\d{8}-\d{3,8}"

_PATIENT_NUMBER = re.compile(r"\b(" + PATIENT_NUMBER_PATTERN + r")\b", re.IGNORECASE)
_VISIT_NUMBER = re.compile(r"\b(" + VISIT_NUMBER_PATTERN + r")\b", re.IGNORECASE)

# Date windows are resolved from a fixed phrase table, never parsed loosely and
# never taken from the model. Anything unrecognised falls back to today, which
# is both the most common intent and the narrowest window.
_TODAY = frozenset({"today", "leo", "now", "currently", "sasa"})
_YESTERDAY = frozenset({"yesterday", "jana"})
_WEEK = frozenset({"week", "weekly", "wiki", "7", "seven"})
_MONTH = frozenset({"month", "monthly", "mwezi", "30", "thirty"})

# The same ceiling admin-service/app/services/reports.py::_parse_range applies.
MAX_WINDOW_DAYS = 366


@dataclass(frozen=True)
class RoutedMetric:
    """One metric the router selected, with the parameters it will be run with."""

    definition: MetricDefinition
    params: MetricParams
    score: int


def resolve_window(question: str, today: date | None = None) -> tuple[date, date]:
    """Resolve a date window from the question. Defaults to today.

    Deterministic and bounded: the result is always a real window no wider than
    MAX_WINDOW_DAYS, whatever the question said.
    """
    anchor = today or date.today()
    terms = _tokenize(expand_query(question or ""))

    if terms & _MONTH:
        start, end = anchor - timedelta(days=30), anchor
    elif terms & _WEEK:
        start, end = anchor - timedelta(days=7), anchor
    elif terms & _YESTERDAY:
        start = end = anchor - timedelta(days=1)
    else:
        start = end = anchor

    if (end - start).days > MAX_WINDOW_DAYS:
        start = end - timedelta(days=MAX_WINDOW_DAYS)
    return start, end


def match_known_value(question: str, known: list[str]) -> str | None:
    """Match a question against values that already exist in the tenant database.

    The candidate list is read from the database, so this can only ever return a
    value that is already there. A ward or drug named in a question but absent
    from the hospital resolves to None, and the caller runs the unfiltered
    metric instead of binding an invented value.

    Longest match wins, so "Maternity Annex" is preferred over "Maternity".
    """
    if not question or not known:
        return None
    haystack = question.lower()
    best: str | None = None
    for value in known:
        candidate = (value or "").strip()
        if len(candidate) < 3:
            continue
        if candidate.lower() in haystack:
            if best is None or len(candidate) > len(best):
                best = candidate
    return best


def extract_identifiers(question: str) -> tuple[str | None, str | None]:
    """Pull a patient number and a visit number out of a question, if present."""
    if not question:
        return None, None
    patient = _PATIENT_NUMBER.search(question)
    visit = _VISIT_NUMBER.search(question)
    # Upper-cased so a question typed in lower case binds the value the column
    # actually holds. The two prefixes are disjoint, so unlike the loose patterns
    # these replaced, one string can no longer match as both.
    patient_number = patient.group(1).upper() if patient else None
    visit_number = visit.group(1).upper() if visit else None
    return patient_number, visit_number


def resolve_queue_type(question: str) -> str | None:
    """Resolve which queue a question is about, from a fixed synonym map.

    queue_type is a database enum rather than tenant data, so unlike a ward name
    it needs no lookup: the six values cannot vary between hospitals. Matching is
    done on expanded tokens so a Swahili question resolves the same way.
    """
    from app.assistant.live.catalog.flow import QUEUE_TYPE_SYNONYMS

    if not question:
        return None
    terms = _tokenize(expand_query(question))
    for term in sorted(terms):
        resolved = QUEUE_TYPE_SYNONYMS.get(term)
        if resolved:
            return resolved
    return None


def _score(definition: MetricDefinition, terms: set[str]) -> int:
    """Overlap between a question's terms and a metric's trigger terms."""
    if not terms:
        return 0
    return len(terms & definition.triggers)


def route(
    question: str,
    roles: frozenset[str],
    actor_sub: str | None = None,
    is_super_admin: bool = False,
    limit: int = 3,
    known_wards: list[str] | None = None,
    known_drugs: list[str] | None = None,
    today: date | None = None,
    assume_named_values: bool = False,
    resolved_patient_number: str | None = None,
) -> list[RoutedMetric]:
    """Select the metrics to run for one question. Fail-closed.

    Role filtering runs before scoring, so a low-scoring permitted metric can be
    dropped but a forbidden one can never be promoted. A question matching
    nothing returns an empty list and the answer falls back to content only,
    which is exactly today's behaviour.
    """
    if not question or not roles:
        return []

    terms = _tokenize(expand_query(question))
    if not terms:
        return []

    start, end = resolve_window(question, today=today)
    patient_number, visit_number = extract_identifiers(question)
    # A number written in the question always wins over one the server resolved
    # from a name. The caller who typed an identifier has said exactly who they
    # mean, and a name match must never override that.
    if not patient_number and resolved_patient_number:
        patient_number = resolved_patient_number
    ward_name = match_known_value(question, known_wards or [])
    drug_name = match_known_value(question, known_drugs or [])
    queue_type = resolve_queue_type(question)

    candidates: list[RoutedMetric] = []
    for definition in permitted_metrics(roles, is_super_admin=is_super_admin):
        # A patient-tier metric needs an explicit identifier in the question.
        if definition.tier is MetricTier.PATIENT and not (patient_number or visit_number):
            continue
        # A worklist metric is meaningless without a verified subject to bind.
        if definition.tier is MetricTier.WORKLIST and not actor_sub:
            continue
        # A metric that filters on a ward is only useful once a real ward name
        # has been resolved; otherwise its unfiltered sibling covers the question.
        #
        # assume_named_values is for the caller's first, cheap pass, which only
        # decides whether reading the tenant's ward and drug names is worth a
        # query. Applying these skips there would beg the question: a metric that
        # needs a drug name can never match before the drug names are loaded, so
        # "do we have any amoxicillin left" - which matches no other metric -
        # would look like a question about nothing and never load them at all.
        if not assume_named_values:
            if "ward_name" in definition.params and not ward_name:
                continue
            if "drug_name" in definition.params and not drug_name:
                continue
        if "queue_type" in definition.params and not queue_type:
            continue
        # The same rule for the two identifiers, and for the same reason. A
        # metric keyed by visit number that runs with none binds NULL, matches
        # nobody, and answers "no visit recorded" about a patient who is sitting
        # in a queue. The tier check above only asks whether *an* identifier was
        # found; this asks whether the one this particular metric needs was.
        if "patient_number" in definition.params and not patient_number:
            continue
        if "visit_number" in definition.params and not visit_number:
            continue

        score = _score(definition, terms)
        # A question that names a patient number is a question about that
        # patient, whatever else it says. Trigger words cannot carry that on
        # their own: "where", "patient" and "patients" are all stopwords in
        # retrieval._tokenize, so "where is patient PT-20260829-0001" tokenises
        # to the digits of the number and nothing else, and a patient-tier
        # metric would score zero on the one question it exists to answer. The
        # identifier is the topic, so it is worth a point. This can only promote
        # a metric whose role gate the caller has already passed, and only once
        # the identifier it needs has resolved.
        if definition.tier is MetricTier.PATIENT:
            score += 1
        if score <= 0:
            continue

        candidates.append(
            RoutedMetric(
                definition=definition,
                params=MetricParams(
                    start=start,
                    end=end,
                    ward_name=ward_name,
                    drug_name=drug_name,
                    queue_type=queue_type,
                    patient_number=patient_number,
                    visit_number=visit_number,
                    actor_sub=actor_sub,
                ),
                score=score,
            )
        )

    # Highest score first, then metric id, so selection never depends on set
    # iteration order and the same question always runs the same metrics.
    candidates.sort(key=lambda c: (-c.score, c.definition.metric_id))
    return candidates[: max(0, int(limit))]
