apiVersion: v1
kind: Service
metadata:
  name: clinical-decision-support-service
spec:
  selector:
    app: clinical-decision-support-service
  ports:
    - protocol: TCP
      port: 8021
      targetPort: 8021
  type: ClusterIP
